server:
  port: 8002
spring:
  application:
    name: Taobao-cart
  redis:
    host: 116.62.38.97
    port: 63799
    password: root
    lettuce:
      shutdown-timeout: 200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: provider-cart

ribbon:
  eureka:
    enabled: true
