server:
  port: 8003
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taobao?useSSL=false
    username: root
    password: root
  application:
    name: Taobao-Order

mybatis:
  mapper-locations: classpath*:providerorder8003/*Mapper.xml
  type-aliases-package: com.wzh.common_api.entity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: provider-order
